Update jenkinsfile1

diff --git a/jenkinsfile1 b/jenkinsfile1
--- a/jenkinsfile1
+++ b/jenkinsfile1
@@ -16,10 +16,8 @@ pipeline {
              steps{
 		 sh ''' 
                      sfcc-ci client:auth dd8b0698-f881-4065-8bb6-2e554aefdd73 sandboxes123!
-		     def rc=$?
-                     if ($rc != 0) then {
-                     error 'Salesforce dev hub org authorization failed.'
-                          }
+		     if [ $? != 0 ]; then
+                       echo 'Salesforce dev hub org authorization failed.'
 	             fi
                  '''
 		}   
